name: Deploy PR Preview to Netlify

on:
  pull_request:
    branches:
      - main # Runs only when a PR is created for main

permissions:
  pull-requests: write
  deployments: write
  statuses: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Environment Variables
        run: |
          echo "NUXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NUXT_PUBLIC_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NUXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NUXT_PUBLIC_FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "NUXT_ENCRYPTION_SECRET_KEY=${{ secrets.NUXT_ENCRYPTION_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm ci

      - name: Build Nuxt App
        run: npm run build

      - name: Deploy PR Preview to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./.output/public"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "🚀 Deploying PR Preview to Netlify"
          alias: pr-${{ github.event.number }}
          enable-pull-request-comment: true
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
