name: CBT

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      # - name: Run Unit Tests
      #   run: npm run test

      - name: Build Nuxt App
        run: npm run build
