name: CBT Tests

on:
  push:
    branches:
      - dev # Runs only when code is pushed to dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ✅ Clones your repository into the GitHub Actions runner
      - name: 🚀 Checkout Repository
        uses: actions/checkout@v4

      # ✅ Sets environment variables using GitHub Secrets
      - name: 🔑 Set Firebase Environment Variables
        run: |
          echo "NUXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NUXT_PUBLIC_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NUXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NUXT_PUBLIC_FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "NUXT_ENCRYPTION_SECRET_KEY=${{ secrets.NUXT_ENCRYPTION_SECRET_KEY }}" >> $GITHUB_ENV

      # ✅ Sets up Node.js with caching for faster builds
      - name: ⚡ Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # ✅ Installs dependencies
      - name: 📦 Install Dependencies
        run: npm ci

      # ✅ Runs Vitest unit tests
      - name: ✅ Run Unit Tests
        run: npm run test
